from enum import Enum


class Currency3Code(Enum):
    """
    ISO 4217
    """
    BurundianFranc = 'BIF'  # https://en.wikipedia.org/wiki/Burundian_franc
    GuyaneseDollar = 'GYD'  # https://en.wikipedia.org/wiki/Guyanese_dollar
    SamoanTala = 'WST'  # https://en.wikipedia.org/wiki/Samoan_t%C4%81l%C4%81
    PapuaNewGuineanKina = 'PGK'  # https://www.google.com/search?q=PGK+currency&sca_esv=0f1789b80fec1324&biw=1870&bih=961&sxsrf=ANbL-n7mCBpXCD8hw5DdEN8oEOyCFXRh5A%3A1773790968817&ei=-Oa5aZLLMbaBi-gPyPDXgAY&ved=0ahUKEwiSp-ikjqiTAxW2wAIHHUj4FWAQ4dUDCBE&uact=5&oq=PGK+currency&gs_lp=Egxnd3Mtd2l6LXNlcnAiDFBHSyBjdXJyZW5jeTIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeMgYQABgHGB4yBhAAGAcYHjIGEAAYBxgeSP0JUPUCWPUCcAJ4AZABAJgBdKABdKoBAzAuMbgBA8gBAPgBAvgBAZgCA6ACnAHCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBZgDAIgGAZAGCpIHAzIuMaAH7QWyBwMwLjG4B4MBwgcDMy0zyAcggAgA&sclient=gws-wiz-serp#:~:text=Web%20results-,Papua%20New%20Guinean%20kina,-Wikipedia
    LibyanDinar = 'LYD'  # https://en.wikipedia.org/wiki/Libyan_dinar
    EthiopianBirr = 'ETB'  # https://en.wikipedia.org/wiki/Ethiopian_birr
    CentralAfricanCFAFranc = 'XAF'  # https://en.wikipedia.org/wiki/Central_African_CFA_franc
    AfghanAfghani = 'AFN'  # https://en.wikipedia.org/wiki/Afghan_afghani
    SwaziLilangeni = 'SZL'  # https://en.wikipedia.org/wiki/Swazi_lilangeni
    TanzanianShilling = 'TZS'  # https://en.wikipedia.org/wiki/Tanzanian_shilling
    CapeVerdeanEscudo = 'CVE'  # https://en.wikipedia.org/wiki/Cape_Verdean_escudo
    BhutaneseNgultrum = 'BTN'  # https://en.wikipedia.org/wiki/Bhutanese_ngultrum
    SudanesePound = 'SDG'  # https://en.wikipedia.org/wiki/Sudanese_pound
    MaldivianRufiyaa = 'MVR'  # https://en.wikipedia.org/wiki/Maldivian_rufiyaa
    BruneiDollar = 'BND'  # https://en.wikipedia.org/wiki/Brunei_dollar
    WestAfricanCFAFranc = 'CFA'  # https://en.wikipedia.org/wiki/West_African_CFA_franc
    RussianRuble = 'RUB'
    TajikistaniSomoni = 'TJS'
    Euro = 'EUR'
    UnitedStatesDollar = 'USD'
    NewZealandDollar = 'NZD'
    QatariRiyal = 'QAR'
    GreatBritishPound = 'GBP'
    GeorgianLari = 'GEL'
    UzbekistaniSum = 'UZS'
    BelarusianRuble = 'BYN'
    BitCoin = 'BTC'
    BosniaConvertibleMark = 'BAM'  # https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina_convertible_mark
    DominicanPeso = 'DOP'
    MexicanPeso = 'MXN'
    ChineseYuan = 'CNY'
    JapaneseYen = 'JPY'
    IndianRupee = 'INR'
    SouthKoreanWon = 'KRW'
    EmiratesDirham = 'AED'
    KuwaitiDinar = 'KWD'
    AustraliaDollar = 'AUD'
    CanadianDollar = 'CAD'
    UkrainianHryvnia = 'UAH'
    CzechKoruna = 'CZK'
    TurkishLire = 'TRY'
    SerbianDinar = 'RSD'
    SingaporeDollar = 'SGD'
    ArgentinePesos = 'ARS'
    BrazilianReal = 'BRL'
    PeruvianSol = 'PEN'
    CubanPeso = 'CUP'
    VietnameseDongs = 'VND'
    EgyptianPound = 'EGP'
    BarbadianDollar = 'BBD'
    SwissFranc = 'CHF'
    IndonesianRupiah = 'IDR'
    MalaysianRinggit = 'MYR'
    MauritianRupee = 'MUR'
    SriLankanRupee = 'LKR'
    ThaiBaht = 'THB'
    ColombianPeso = 'COP'
    PhilippinePeso = 'PHP'
    MoroccanDirham = 'MAD'
    UruguayanPeso = 'UYU'
    IsraeliNewShekels = 'ILS'
    SouthAfricanRand = 'ZAR'
    CostaRicanColones = 'CRC'
    GuatemalanQuetzale = 'GTQ'
    PanamanianBalboa = 'PAB'
    TrinidadAndTobagoDollar = 'TTD'
    PolishZlotych = 'PLN'
    EastCaribbeanDollar = 'XCD'
    ArubanFlorin = 'AWG'
    AntilleanGuilder = 'ANG'
    JamaicanDollar = 'JMD'
    BelizeDollar = 'BZD'
    ChileanPeso = 'CLP'
    BulgarianLev = 'BGN'
    AlbanianLek = 'ALL'
    NorwegianKrone = 'NOK'
    HongKongDollar = 'HKD'
    TunisianDinar = 'TND'
    NigerianNaira = 'NGN'
    AlgerianDinar = 'DZD'
    UgandanShilling = 'UGX'
    CFAFranc = 'XOF'
    KenyanShilling = 'KES'
    GhanaianCedi = 'GHS'
    HaitianGourde = 'HTG'
    HungarianForint = 'HUF'
    IcelandicKrona = 'ISK'
    KazakhstaniTenge = 'KZT'
    SwedishKrona = 'SEK'
    MalawianKwacha = 'MWK'
    BahrainiDinar = 'BHD'
    PakistaniRupee = 'PKR'
    NicaraguanCordoba = 'NIO'
    MacanesePataca = 'MOP'
    DanishKrone = 'DKK'
    OmaniRial = 'OMR'
    GibraltarPound = 'GIP'
    BangladeshiTaka = 'BDT'
    BahamianDollar = 'BSD'
    HonduranLempira = 'HNL'
    SierraLeoneanLeones = 'SLL'
    VanuatuVatu = 'VUV'
    NepaleseRupee = 'NPR'
    MalagasyAriary = 'MGA'
    CroatianKuna = 'HRK'
    GambianDalasi = 'GMD'
    ZambianKwacha = 'ZMW'
    SyrianPound = 'SYP'
    SaudiRiyal = 'SAR'
    AzerbaijaniManat = 'AZN'
    NamibianDollar = 'NAD'
    CaymanIslandsDollar = 'KYD'
    SeychelloisRupee = 'SCR'
    IranianRiyal = 'IRR'
    IraqiDinar = 'IQD'
    JordanianDinar = 'JOD'
    LebanesePound = 'LBP'
    YemeniRiyal = 'YER'
    MyanmarKyat = 'MMK'
    RomanianLeuNew = 'RON'
    TaiwanDollarNew = 'TWD'
    MongolianTughrik = 'MNT'
    BolivianBoliviano = 'BOB'
    BermudianDollar = 'BMD'
    ParaguayanGuarani = 'PYG'
    ArmenianDram = 'AMD'
    AngolanKwanza = 'AOA'
    
    ZRX = 'ZRX'
    GoldCoin = 'GLC'
    
    def __str__(self) -> str:
        return self.value
