from enum import Enum


class CountryAlpha2Code(Enum):
    # Africa
    Algeria = 'DZ'
    Angola = 'AO'
    Benin = 'BJ'
    Botswana = 'BW'
    BurkinaFaso = 'BF'
    Burundi = 'BI'
    CaboVerde = 'CV'
    CaymanIslands = 'KY'
    Cameroon = 'CM'
    CentralAfricanRepublic = 'CF'
    Chad = 'TD'
    Comoros = 'KM'
    Congo = 'CG'
    CongoDRC = 'CD'
    CoteDIvoire = 'CI'
    Djibouti = 'DJ'
    Egypt = 'EG'
    EquatorialGuinea = 'GQ'
    Eritrea = 'ER'
    Eswatini = 'SZ'
    Ethiopia = 'ET'
    Gabon = 'GA'
    Gambia = 'GM'
    Ghana = 'GH'
    Guinea = 'GN'
    GuineaBissau = 'GW'
    Kenya = 'KE'
    Lesotho = 'LS'
    Liberia = 'LR'
    Libya = 'LY'
    Madagascar = 'MG'
    Malawi = 'MW'
    Mali = 'ML'
    Mauritania = 'MR'
    Mauritius = 'MU'
    Morocco = 'MA'
    Mozambique = 'MZ'
    Namibia = 'NA'
    Niger = 'NE'
    Nigeria = 'NG'
    Rwanda = 'RW'
    SaoTomeAndPrincipe = 'ST'
    Senegal = 'SN'
    Seychelles = 'SC'
    SierraLeone = 'SL'
    Somalia = 'SO'
    SouthAfrica = 'ZA'
    SouthSudan = 'SS'
    Sudan = 'SD'
    Tanzania = 'TZ'
    Togo = 'TG'
    Tunisia = 'TN'
    Uganda = 'UG'
    Zambia = 'ZM'
    Zimbabwe = 'ZW'
    
    # Oceania
    AmericanSamoa = 'AS'
    Australia = 'AU'
    CookIslands = 'CK'
    Fiji = 'FJ'
    FaroeIslands = 'FO'
    FrenchPolynesia = 'PF'
    Micronesia = 'FM'
    Guam = 'GU'
    Kiribati = 'KI'
    MarshallIslands = 'MH'
    Nauru = 'NR'
    NewCaledonia = 'NC'
    NewZealand = 'NZ'
    Niue = 'NU'
    NorfolkIsland = 'NF'
    Palau = 'PW'
    PapuaNewGuinea = 'PG'
    PitcairnIslands = 'PN'
    Samoa = 'WS'
    SolomonIslands = 'SB'
    Tokelau = 'TK'
    Tonga = 'TO'
    Tuvalu = 'TV'
    Vanuatu = 'VU'
    WallisAndFutuna = 'WF'
    
    # Asia
    Afghanistan = 'AF'
    Armenia = 'AM'
    Azerbaijan = 'AZ'
    Bangladesh = 'BD'
    Bhutan = 'BT'
    Brunei = 'BN'
    Cambodia = 'KH'
    China = 'CN'
    India = 'IN'
    Indonesia = 'ID'
    HongKong = 'HK'
    Japan = 'JP'
    Kyrgyzstan = 'KG'
    Laos = 'LA'
    Macao = 'MO'
    Malaysia = 'MY'
    Maldives = 'MV'
    Mongolia = 'MN'
    Myanmar = 'MM'
    Nepal = 'NP'
    NorthKorea = 'KP'
    Pakistan = 'PK'
    Philippines = 'PH'
    Singapore = 'SG'
    SouthKorea = 'KR'
    SriLanka = 'LK'
    Syria = 'SY'
    Taiwan = 'TW'
    Tajikistan = 'TJ'
    Thailand = 'TH'
    Turkmenistan = 'TM'
    Uzbekistan = 'UZ'
    Vietnam = 'VN'
    VietNam = 'VN'
    
    # NA
    Bahamas = 'BS'
    Bermuda = 'BM'
    Canada = 'CA'
    Greenland = 'GL'
    SaintPierreAndMiquelon = 'PM'
    UnitedStatesOfAmerica = 'US'
    PuertoRico = 'PR'
    VirginIslandsBritish = 'VG'
    VirginIslandsUSA = 'VI'
    
    # LATAM
    AntiguaBarbuda = 'AG'
    Anguilla = 'AI'
    Argentina = 'AR'
    Aruba = 'AW'
    Barbados = 'BB'
    Belize = 'BZ'
    Bolivia = 'BO'
    Bonaire = 'BQ'
    Brazil = 'BR'
    Chile = 'CL'
    Colombia = 'CO'
    CostaRica = 'CR'
    Cuba = 'CU'
    Curacao = 'CW'
    DominicanRepublic = 'DO'
    Dominica = 'DM'
    Ecuador = 'EC'
    Salvador = 'SV'
    Grenada = 'GD'
    Guatemala = 'GT'
    Guadeloupe = 'GP'
    Guyana = 'GY'
    Honduras = 'HN'
    Haiti = 'HT'
    Jamaica = 'JM'
    SaintKittsAndNevis = 'KN'
    SaintLucia = 'LC'
    SaintMartin = 'MF'
    SaintBarthelemy = 'BL'
    Suriname = 'SR'
    TurksAndCaicosIslands = 'TC'
    Mexico = 'MX'
    Montserrat = 'MS'
    Nicaragua = 'NI'
    Panama = 'PA'
    Paraguay = 'PY'
    Peru = 'PE'
    Uruguay = 'UY'
    SaintVincentAndTheGrenadines = 'VC'
    TrinidadAndTobago = 'TT'
    Venezuela = 'VE'
    
    # Europe
    Albania = 'AL'
    Andorra = 'AD'
    Austria = 'AT'
    Belarus = 'BY'
    Belgium = 'BE'
    BosniaAndHerzegovina = 'BA'
    Bulgaria = 'BG'
    Croatia = 'HR'
    Cyprus = 'CY'
    Czechia = 'CZ'
    Denmark = 'DK'
    Estonia = 'EE'
    Finland = 'FI'
    France = 'FR'
    Georgia = 'GE'
    Germany = 'DE'
    Gibraltar = 'GI'
    Greece = 'GR'
    Hungary = 'HU'
    Iceland = 'IS'
    Ireland = 'IE'
    Italia = 'IT'
    Italy = 'IT'
    Kazakhstan = 'KZ'
    Latvia = 'LV'
    Liechtenstein = 'LI'
    Lithuania = 'LT'
    Luxembourg = 'LU'
    Malta = 'MT'
    Martinique = 'MQ'
    Moldova = 'MD'
    Monaco = 'MC'
    Montenegro = 'ME'
    Netherlands = 'NL'
    NorthMacedonia = 'MK'
    Norway = 'NO'
    Poland = 'PL'
    Portugal = 'PT'
    Romania = 'RO'
    RussianFederation = 'RU'
    SanMarino = 'SM'
    Serbia = 'RS'
    Slovakia = 'SK'
    Slovenia = 'SI'
    Spain = 'ES'
    Sweden = 'SE'
    Switzerland = 'CH'
    Turkey = 'TR'
    Ukraine = 'UA'
    UnitedKingdom = 'GB'
    VaticanCity = 'VA'
    
    # Middle East
    UnitedArabEmirates = 'AE'
    Bahrain = 'BH'
    Iran = 'IR'
    Iraq = 'IQ'
    Israel = 'IL'
    Jordan = 'JO'
    Kuwait = 'KW'
    Lebanon = 'LB'
    Oman = 'OM'
    Palestine = 'PS'
    Qatar = 'QA'
    SaudiArabia = 'SA'
    SyrianArabRepublic = 'SY'
    Yemen = 'YE'
    
    #
    
    Guernsey = 'GG'
    Jersey = 'JE'
    
    #
    # Alias
    #
    
    USA = UnitedStatesOfAmerica
    UAE = UnitedArabEmirates
    CzechRepublic = Czechia
    Russia = RussianFederation
    UK = UnitedKingdom
    
    def __str__(self) -> str:
        return self.value.__str__()
    
    def __repr__(self) -> str:
        return self.value
