from typing import List

from scrape_core.contract.prime.country_code.country_code import CountryAlpha2Code


def get_all_from_africa() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.Algeria,
        CountryAlpha2Code.Angola,
        CountryAlpha2Code.Benin,
        CountryAlpha2Code.Botswana,
        CountryAlpha2Code.BurkinaFaso,
        CountryAlpha2Code.Burundi,
        CountryAlpha2Code.CaboVerde,
        CountryAlpha2Code.Cameroon,
        CountryAlpha2Code.CentralAfricanRepublic,
        CountryAlpha2Code.Chad,
        CountryAlpha2Code.Comoros,
        CountryAlpha2Code.Congo,
        CountryAlpha2Code.CongoDRC,
        CountryAlpha2Code.CoteDIvoire,
        CountryAlpha2Code.Djibouti,
        CountryAlpha2Code.Egypt,
        CountryAlpha2Code.EquatorialGuinea,
        CountryAlpha2Code.Eritrea,
        CountryAlpha2Code.Eswatini,
        CountryAlpha2Code.Ethiopia,
        CountryAlpha2Code.Gabon,
        CountryAlpha2Code.Gambia,
        CountryAlpha2Code.Ghana,
        CountryAlpha2Code.Guinea,
        CountryAlpha2Code.GuineaBissau,
        CountryAlpha2Code.Kenya,
        CountryAlpha2Code.Lesotho,
        CountryAlpha2Code.Liberia,
        CountryAlpha2Code.Libya,
        CountryAlpha2Code.Madagascar,
        CountryAlpha2Code.Malawi,
        CountryAlpha2Code.Mali,
        CountryAlpha2Code.Mauritania,
        CountryAlpha2Code.Mauritius,
        CountryAlpha2Code.Morocco,
        CountryAlpha2Code.Mozambique,
        CountryAlpha2Code.Namibia,
        CountryAlpha2Code.Niger,
        CountryAlpha2Code.Nigeria,
        CountryAlpha2Code.Rwanda,
        CountryAlpha2Code.SaoTomeAndPrincipe,
        CountryAlpha2Code.Senegal,
        CountryAlpha2Code.Seychelles,
        CountryAlpha2Code.SierraLeone,
        CountryAlpha2Code.Somalia,
        CountryAlpha2Code.SouthAfrica,
        CountryAlpha2Code.SouthSudan,
        CountryAlpha2Code.Sudan,
        CountryAlpha2Code.Tanzania,
        CountryAlpha2Code.Togo,
        CountryAlpha2Code.Tunisia,
        CountryAlpha2Code.Uganda,
        CountryAlpha2Code.Zambia,
        CountryAlpha2Code.Zimbabwe,
    ]


def get_all_from_na() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.Bermuda,
        CountryAlpha2Code.Canada,
        CountryAlpha2Code.Greenland,
        CountryAlpha2Code.SaintPierreAndMiquelon,
        CountryAlpha2Code.UnitedStatesOfAmerica,
        CountryAlpha2Code.PuertoRico,
        CountryAlpha2Code.VirginIslandsBritish,
        CountryAlpha2Code.VirginIslandsUSA,
    ]


def get_all_from_latam() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.AntiguaBarbuda,
        CountryAlpha2Code.Argentina,
        CountryAlpha2Code.Aruba,
        CountryAlpha2Code.Barbados,
        CountryAlpha2Code.Belize,
        CountryAlpha2Code.Brazil,
        CountryAlpha2Code.Chile,
        CountryAlpha2Code.Colombia,
        CountryAlpha2Code.CostaRica,
        CountryAlpha2Code.Cuba,
        CountryAlpha2Code.Curacao,
        CountryAlpha2Code.DominicanRepublic,
        CountryAlpha2Code.Dominica,
        CountryAlpha2Code.Ecuador,
        CountryAlpha2Code.Salvador,
        CountryAlpha2Code.Grenada,
        CountryAlpha2Code.Guatemala,
        CountryAlpha2Code.Honduras,
        CountryAlpha2Code.Haiti,
        CountryAlpha2Code.Jamaica,
        CountryAlpha2Code.SaintKittsAndNevis,
        CountryAlpha2Code.SaintLucia,
        CountryAlpha2Code.Mexico,
        CountryAlpha2Code.Nicaragua,
        CountryAlpha2Code.Panama,
        CountryAlpha2Code.Peru,
        CountryAlpha2Code.Uruguay,
        CountryAlpha2Code.SaintVincentAndTheGrenadines,
        CountryAlpha2Code.TrinidadAndTobago,
        CountryAlpha2Code.Venezuela,
    ]


def get_all_from_europe() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.Albania,
        CountryAlpha2Code.Andorra,
        CountryAlpha2Code.Austria,
        CountryAlpha2Code.Belarus,
        CountryAlpha2Code.Belgium,
        CountryAlpha2Code.BosniaAndHerzegovina,
        CountryAlpha2Code.Bulgaria,
        CountryAlpha2Code.Croatia,
        CountryAlpha2Code.Cyprus,
        CountryAlpha2Code.Czechia,
        CountryAlpha2Code.Denmark,
        CountryAlpha2Code.Estonia,
        CountryAlpha2Code.Finland,
        CountryAlpha2Code.France,
        CountryAlpha2Code.Georgia,
        CountryAlpha2Code.Germany,
        CountryAlpha2Code.Greece,
        CountryAlpha2Code.Hungary,
        CountryAlpha2Code.Iceland,
        CountryAlpha2Code.Ireland,
        CountryAlpha2Code.Italia,
        CountryAlpha2Code.Kazakhstan,
        CountryAlpha2Code.Latvia,
        CountryAlpha2Code.Liechtenstein,
        CountryAlpha2Code.Lithuania,
        CountryAlpha2Code.Luxembourg,
        CountryAlpha2Code.Malta,
        CountryAlpha2Code.Moldova,
        CountryAlpha2Code.Monaco,
        CountryAlpha2Code.Montenegro,
        CountryAlpha2Code.Netherlands,
        CountryAlpha2Code.NorthMacedonia,
        CountryAlpha2Code.Norway,
        CountryAlpha2Code.Poland,
        CountryAlpha2Code.Portugal,
        CountryAlpha2Code.Romania,
        CountryAlpha2Code.RussianFederation,
        CountryAlpha2Code.SanMarino,
        CountryAlpha2Code.Serbia,
        CountryAlpha2Code.Slovakia,
        CountryAlpha2Code.Slovenia,
        CountryAlpha2Code.Spain,
        CountryAlpha2Code.Sweden,
        CountryAlpha2Code.Switzerland,
        CountryAlpha2Code.Turkey,
        CountryAlpha2Code.Ukraine,
        CountryAlpha2Code.UnitedKingdom,
        CountryAlpha2Code.VaticanCity,
    ]


def get_all_from_middle_east() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.UnitedArabEmirates,
        CountryAlpha2Code.Bahrain,
        CountryAlpha2Code.Iran,
        CountryAlpha2Code.Iraq,
        CountryAlpha2Code.Israel,
        CountryAlpha2Code.Jordan,
        CountryAlpha2Code.Kuwait,
        CountryAlpha2Code.Lebanon,
        CountryAlpha2Code.Oman,
        CountryAlpha2Code.Palestine,
        CountryAlpha2Code.Qatar,
        CountryAlpha2Code.SaudiArabia,
        CountryAlpha2Code.SyrianArabRepublic,
        CountryAlpha2Code.Yemen,
    ]


def get_all_from_asia() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.Afghanistan,
        CountryAlpha2Code.Armenia,
        CountryAlpha2Code.Azerbaijan,
        CountryAlpha2Code.Bangladesh,
        CountryAlpha2Code.Bhutan,
        CountryAlpha2Code.Brunei,
        CountryAlpha2Code.Cambodia,
        CountryAlpha2Code.China,
        CountryAlpha2Code.India,
        CountryAlpha2Code.Indonesia,
        CountryAlpha2Code.Japan,
        CountryAlpha2Code.Kyrgyzstan,
        CountryAlpha2Code.Laos,
        CountryAlpha2Code.Macao,
        CountryAlpha2Code.Malaysia,
        CountryAlpha2Code.Maldives,
        CountryAlpha2Code.Mongolia,
        CountryAlpha2Code.Myanmar,
        CountryAlpha2Code.Nepal,
        CountryAlpha2Code.NorthKorea,
        CountryAlpha2Code.Pakistan,
        CountryAlpha2Code.Philippines,
        CountryAlpha2Code.Singapore,
        CountryAlpha2Code.SouthKorea,
        CountryAlpha2Code.SriLanka,
        CountryAlpha2Code.Syria,
        CountryAlpha2Code.Tajikistan,
        CountryAlpha2Code.Thailand,
        CountryAlpha2Code.Turkmenistan,
        CountryAlpha2Code.Uzbekistan,
        CountryAlpha2Code.Vietnam,
    ]


def get_all_from_oceania() -> List[CountryAlpha2Code]:
    return [
        CountryAlpha2Code.AmericanSamoa,
        CountryAlpha2Code.Australia,
        CountryAlpha2Code.CookIslands,
        CountryAlpha2Code.Fiji,
        CountryAlpha2Code.Micronesia,
        CountryAlpha2Code.Guam,
        CountryAlpha2Code.Kiribati,
        CountryAlpha2Code.MarshallIslands,
        CountryAlpha2Code.Nauru,
        CountryAlpha2Code.NewCaledonia,
        CountryAlpha2Code.NewZealand,
        CountryAlpha2Code.Niue,
        CountryAlpha2Code.NorfolkIsland,
        CountryAlpha2Code.Palau,
        CountryAlpha2Code.PapuaNewGuinea,
        CountryAlpha2Code.PitcairnIslands,
        CountryAlpha2Code.Samoa,
        CountryAlpha2Code.SolomonIslands,
        CountryAlpha2Code.Tokelau,
        CountryAlpha2Code.Tonga,
        CountryAlpha2Code.Tuvalu,
        CountryAlpha2Code.Vanuatu,
        CountryAlpha2Code.WallisAndFutuna,
    ]
