from .country_code import CountryAlpha2Code

country_name_to_code__en = {
    'Venezuela': CountryAlpha2Code.Venezuela,
    'Kuwait': CountryAlpha2Code.Kuwait,
    'Iran': CountryAlpha2Code.Iran,
    'Bahrain': CountryAlpha2Code.Bahrain,
    'Egypt': CountryAlpha2Code.Egypt,
    'Kazakhstan': CountryAlpha2Code.Kazakhstan,
    'Malaysia': CountryAlpha2Code.Malaysia,
    'Bolivia': CountryAlpha2Code.Bolivia,
    'Qatar': CountryAlpha2Code.Qatar,
    'Belarus': CountryAlpha2Code.Belarus,
    'Trinidad And Tobago': CountryAlpha2Code.TrinidadAndTobago,
    'Indonesia': CountryAlpha2Code.Indonesia,
    'Oman': CountryAlpha2Code.Oman,
    'Nigeria': CountryAlpha2Code.Nigeria,
    'Saudi Arabia': CountryAlpha2Code.SaudiArabia,
    'Azerbaijan': CountryAlpha2Code.Azerbaijan,
    'United Arab Emirates': CountryAlpha2Code.UnitedArabEmirates,
    'Vietnam': CountryAlpha2Code.Vietnam,
    'Puerto Rico': CountryAlpha2Code.PuertoRico,
    'Russia': CountryAlpha2Code.RussianFederation,
    'Paraguay': CountryAlpha2Code.Paraguay,
    'Lebanon': CountryAlpha2Code.Lebanon,
    'United States': CountryAlpha2Code.UnitedStatesOfAmerica,
    'China': CountryAlpha2Code.China,
    'El Salvador': CountryAlpha2Code.Salvador,
    'Pakistan': CountryAlpha2Code.Pakistan,
    'Honduras': CountryAlpha2Code.Honduras,
    'Philippines': CountryAlpha2Code.Philippines,
    'Argentina': CountryAlpha2Code.Argentina,
    'Jamaica': CountryAlpha2Code.Jamaica,
    'Guatemala': CountryAlpha2Code.Guatemala,
    'Thailand': CountryAlpha2Code.Thailand,
    'Canada': CountryAlpha2Code.Canada,
    'Sudan': CountryAlpha2Code.Sudan,
    'India': CountryAlpha2Code.India,
    'Colombia': CountryAlpha2Code.Colombia,
    'Peru': CountryAlpha2Code.Peru,
    'Tanzania': CountryAlpha2Code.Tanzania,
    'Haiti': CountryAlpha2Code.Haiti,
    'Malta': CountryAlpha2Code.Malta,
    'Brazil': CountryAlpha2Code.Brazil,
    'Cambodia': CountryAlpha2Code.Cambodia,
    'Japan': CountryAlpha2Code.Japan,
    'South Korea': CountryAlpha2Code.SouthKorea,
    'Australia': CountryAlpha2Code.Australia,
    'Ghana': CountryAlpha2Code.Ghana,
    'Slovenia': CountryAlpha2Code.Slovenia,
    'South Africa': CountryAlpha2Code.SouthAfrica,
    'Mexico': CountryAlpha2Code.Mexico,
    'Chile': CountryAlpha2Code.Chile,
    'Turkey': CountryAlpha2Code.Turkey,
    'Costa Rica': CountryAlpha2Code.CostaRica,
    'Slovakia': CountryAlpha2Code.Slovakia,
    'Nicaragua': CountryAlpha2Code.Nicaragua,
    'Ukraine': CountryAlpha2Code.Ukraine,
    'Bosnia and Herzegovina': CountryAlpha2Code.BosniaAndHerzegovina,
    'Kenya': CountryAlpha2Code.Kenya,
    'Bulgaria': CountryAlpha2Code.Bulgaria,
    'Macedonia': CountryAlpha2Code.NorthMacedonia,
    'New Zealand': CountryAlpha2Code.NewZealand,
    'Montenegro': CountryAlpha2Code.Montenegro,
    'Zimbabwe': CountryAlpha2Code.Zimbabwe,
    'Cyprus': CountryAlpha2Code.Cyprus,
    'Poland': CountryAlpha2Code.Poland,
    'Sweden': CountryAlpha2Code.Sweden,
    'Lithuania': CountryAlpha2Code.Lithuania,
    'Estonia': CountryAlpha2Code.Estonia,
    'Croatia': CountryAlpha2Code.Croatia,
    'Czech Republic': CountryAlpha2Code.CzechRepublic,
    'Romania': CountryAlpha2Code.Romania,
    'Hungary': CountryAlpha2Code.Hungary,
    'Luxembourg': CountryAlpha2Code.Luxembourg,
    'Latvia': CountryAlpha2Code.Latvia,
    'Serbia': CountryAlpha2Code.Serbia,
    'Spain': CountryAlpha2Code.Spain,
    'United Kingdom': CountryAlpha2Code.UnitedKingdom,
    'Austria': CountryAlpha2Code.Austria,
    'Belgium': CountryAlpha2Code.Belgium,
    'Finland': CountryAlpha2Code.Finland,
    'Uruguay': CountryAlpha2Code.Uruguay,
    'Ireland': CountryAlpha2Code.Ireland,
    'Portugal': CountryAlpha2Code.Portugal,
    'Germany': CountryAlpha2Code.Germany,
    'Greece': CountryAlpha2Code.Greece,
    'France': CountryAlpha2Code.France,
    'Italy': CountryAlpha2Code.Italy,
    'Albania': CountryAlpha2Code.Albania,
    'Norway': CountryAlpha2Code.Norway,
    'Switzerland': CountryAlpha2Code.Switzerland,
    'Israel': CountryAlpha2Code.Israel,
    'Denmark': CountryAlpha2Code.Denmark,
    'Netherlands': CountryAlpha2Code.Netherlands,
    'Iceland': CountryAlpha2Code.Iceland,
    'Singapore': CountryAlpha2Code.Singapore,
    'Hong Kong': CountryAlpha2Code.HongKong,
    
    'USA': CountryAlpha2Code.USA,
    
    'georgia': CountryAlpha2Code.Georgia,
    'South_Africa': CountryAlpha2Code.SouthAfrica,
    'Deutschland': CountryAlpha2Code.Germany,
    'New_Zealand': CountryAlpha2Code.NewZealand,
    'Belgien': CountryAlpha2Code.Belgium,
}

country_name_to_code__ru = {
    'Мексика': CountryAlpha2Code.Mexico,
    'Франция': CountryAlpha2Code.France,
    'Италия': CountryAlpha2Code.Italy,
    'Испания': CountryAlpha2Code.Spain,
    'Греция': CountryAlpha2Code.Greece,
    'Австрия': CountryAlpha2Code.Austria,
    'Грузия': CountryAlpha2Code.Georgia,
    'Словения': CountryAlpha2Code.Slovenia,
    'Германия': CountryAlpha2Code.Germany,
    'Армения': CountryAlpha2Code.Armenia,
    'Македония': CountryAlpha2Code.NorthMacedonia,
    'Россия': CountryAlpha2Code.RussianFederation,
    'Шотландия': CountryAlpha2Code.UnitedKingdom,
    'Уэльс': CountryAlpha2Code.UnitedKingdom,
    'Великобритания': CountryAlpha2Code.UnitedKingdom,
    'Индия': CountryAlpha2Code.India,
    'Израиль': CountryAlpha2Code.Israel,
    'Тайвань': CountryAlpha2Code.Taiwan,
    'Ирландия': CountryAlpha2Code.Ireland,
    'Сербия': CountryAlpha2Code.Serbia,
    'США': CountryAlpha2Code.UnitedStatesOfAmerica,
    'Португалия': CountryAlpha2Code.Portugal,
    'ЮАР': CountryAlpha2Code.SouthAfrica,
    'Австралия': CountryAlpha2Code.Australia,
    'Финляндия': CountryAlpha2Code.Finland,
    'Литва': CountryAlpha2Code.Lithuania,
    'Монголия': CountryAlpha2Code.Mongolia,
    'Чили': CountryAlpha2Code.Chile,
    'Аргентина': CountryAlpha2Code.Argentina,
    'Новая Зеландия': CountryAlpha2Code.NewZealand,
    'Ливан': CountryAlpha2Code.Lebanon,
    'Беларусь': CountryAlpha2Code.Belarus,
    'Латвия': CountryAlpha2Code.Latvia,
    'Азербайджан': CountryAlpha2Code.Azerbaijan,
    'Польша': CountryAlpha2Code.Poland,
    'Канада': CountryAlpha2Code.Canada,
    'Перу': CountryAlpha2Code.Peru,
    'Южная Корея': CountryAlpha2Code.SouthKorea,
    'Швеция': CountryAlpha2Code.Sweden,
    'Исландия': CountryAlpha2Code.Iceland,
    'Япония': CountryAlpha2Code.Japan,
    'Китай': CountryAlpha2Code.China,
    'Чехия': CountryAlpha2Code.CzechRepublic,
    'Нидерланды': CountryAlpha2Code.Netherlands,
    
    'Южная Африка': CountryAlpha2Code.SouthAfrica,
    'Соединенные Штаты Америки': CountryAlpha2Code.USA,
    'Панама': CountryAlpha2Code.Panama,
    'Мартиника': CountryAlpha2Code.Martinique,
}


def parse(text: str) -> CountryAlpha2Code | None:
    for name in country_name_to_code__en:
        if name in text:
            return country_name_to_code__en[name]
    
    for  name in country_name_to_code__ru:
        if name in text:
            return country_name_to_code__ru[name]
    
    return None
